// Generated by gencpp from file sus2/AddTwoins.msg
// DO NOT EDIT!


#ifndef SUS2_MESSAGE_ADDTWOINS_H
#define SUS2_MESSAGE_ADDTWOINS_H

#include <ros/service_traits.h>


#include <sus2/AddTwoinsRequest.h>
#include <sus2/AddTwoinsResponse.h>


namespace sus2
{

struct AddTwoins
{

typedef AddTwoinsRequest Request;
typedef AddTwoinsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoins
} // namespace sus2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sus2::AddTwoins > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sus2::AddTwoins&) { return value(); }
};

template<>
struct DataType< ::sus2::AddTwoins > {
  static const char* value()
  {
    return "sus2/AddTwoins";
  }

  static const char* value(const ::sus2::AddTwoins&) { return value(); }
};


// service_traits::MD5Sum< ::sus2::AddTwoinsRequest> should match
// service_traits::MD5Sum< ::sus2::AddTwoins >
template<>
struct MD5Sum< ::sus2::AddTwoinsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sus2::AddTwoins >::value();
  }
  static const char* value(const ::sus2::AddTwoinsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sus2::AddTwoinsRequest> should match
// service_traits::DataType< ::sus2::AddTwoins >
template<>
struct DataType< ::sus2::AddTwoinsRequest>
{
  static const char* value()
  {
    return DataType< ::sus2::AddTwoins >::value();
  }
  static const char* value(const ::sus2::AddTwoinsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sus2::AddTwoinsResponse> should match
// service_traits::MD5Sum< ::sus2::AddTwoins >
template<>
struct MD5Sum< ::sus2::AddTwoinsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sus2::AddTwoins >::value();
  }
  static const char* value(const ::sus2::AddTwoinsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sus2::AddTwoinsResponse> should match
// service_traits::DataType< ::sus2::AddTwoins >
template<>
struct DataType< ::sus2::AddTwoinsResponse>
{
  static const char* value()
  {
    return DataType< ::sus2::AddTwoins >::value();
  }
  static const char* value(const ::sus2::AddTwoinsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUS2_MESSAGE_ADDTWOINS_H
