// Generated by gencpp from file sus2/AddTwoinsRequest.msg
// DO NOT EDIT!


#ifndef SUS2_MESSAGE_ADDTWOINSREQUEST_H
#define SUS2_MESSAGE_ADDTWOINSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sus2
{
template <class ContainerAllocator>
struct AddTwoinsRequest_
{
  typedef AddTwoinsRequest_<ContainerAllocator> Type;

  AddTwoinsRequest_()
    : a(0)
    , b(0)  {
    }
  AddTwoinsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::sus2::AddTwoinsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sus2::AddTwoinsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoinsRequest_

typedef ::sus2::AddTwoinsRequest_<std::allocator<void> > AddTwoinsRequest;

typedef boost::shared_ptr< ::sus2::AddTwoinsRequest > AddTwoinsRequestPtr;
typedef boost::shared_ptr< ::sus2::AddTwoinsRequest const> AddTwoinsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sus2::AddTwoinsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sus2::AddTwoinsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sus2::AddTwoinsRequest_<ContainerAllocator1> & lhs, const ::sus2::AddTwoinsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sus2::AddTwoinsRequest_<ContainerAllocator1> & lhs, const ::sus2::AddTwoinsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sus2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sus2::AddTwoinsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sus2::AddTwoinsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sus2::AddTwoinsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::sus2::AddTwoinsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sus2/AddTwoinsRequest";
  }

  static const char* value(const ::sus2::AddTwoinsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::sus2::AddTwoinsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoinsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sus2::AddTwoinsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sus2::AddTwoinsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUS2_MESSAGE_ADDTWOINSREQUEST_H
