// Generated by gencpp from file sus2/AddTwoinsResponse.msg
// DO NOT EDIT!


#ifndef SUS2_MESSAGE_ADDTWOINSRESPONSE_H
#define SUS2_MESSAGE_ADDTWOINSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sus2
{
template <class ContainerAllocator>
struct AddTwoinsResponse_
{
  typedef AddTwoinsResponse_<ContainerAllocator> Type;

  AddTwoinsResponse_()
    : sum(0)  {
    }
  AddTwoinsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::sus2::AddTwoinsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sus2::AddTwoinsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoinsResponse_

typedef ::sus2::AddTwoinsResponse_<std::allocator<void> > AddTwoinsResponse;

typedef boost::shared_ptr< ::sus2::AddTwoinsResponse > AddTwoinsResponsePtr;
typedef boost::shared_ptr< ::sus2::AddTwoinsResponse const> AddTwoinsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sus2::AddTwoinsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sus2::AddTwoinsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sus2::AddTwoinsResponse_<ContainerAllocator1> & lhs, const ::sus2::AddTwoinsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sus2::AddTwoinsResponse_<ContainerAllocator1> & lhs, const ::sus2::AddTwoinsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sus2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sus2::AddTwoinsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sus2::AddTwoinsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sus2::AddTwoinsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::sus2::AddTwoinsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sus2/AddTwoinsResponse";
  }

  static const char* value(const ::sus2::AddTwoinsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::sus2::AddTwoinsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoinsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sus2::AddTwoinsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sus2::AddTwoinsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUS2_MESSAGE_ADDTWOINSRESPONSE_H
